version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.5
    hostname: spark-master
    networks:
      - spark-net
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_DAEMON_USER=root
      - SPARK_EVENTLOG_ENABLED=yes
      - SPARK_EVENTLOG_DIR=/tmp/spark-events
    volumes:
      - spark-events:/tmp/spark-events
    ports:
      - "7077:7077"
      - "8080:8080"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  spark-worker:
    image: bitnami/spark:3.5
    networks:
      - spark-net
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_DAEMON_USER=root
      - SPARK_EVENTLOG_ENABLED=yes
      - SPARK_EVENTLOG_DIR=/tmp/spark-events
    volumes:
      - spark-events:/tmp/spark-events
    depends_on:
      - spark-master
    deploy:
      replicas: 2

  spark-history:
    image: bitnami/spark:3.5
    hostname: spark-history
    networks:
      - spark-net
    environment:
      - SPARK_MODE=history
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/tmp/spark-events
    volumes:
      - spark-events:/tmp/spark-events
    ports:
      - "18080:18080"
    depends_on:
      - spark-master

  spark-jupyter:
    image: jupyter/all-spark-notebook:latest
    hostname: spark-jupyter
    networks:
      - spark-net
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - JUPYTER_TOKEN=password
    volumes:
      - jupyter-data:/home/jovyan/work
    ports:
      - "8888:8888"
    depends_on:
      - spark-master

  spark-submit:
    image: bitnami/spark:3.5
    networks:
      - spark-net
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - submit-apps:/app
    command: sleep infinity
    depends_on:
      - spark-master

volumes:
  spark-events:
  jupyter-data:
  submit-apps:

networks:
  spark-net:
    driver: overlay
